### PR TITLE
feat(created the about page): created the about page and a card compo…

### LINKED ISSUE #43: The About Page
**Task title**
The About Page

**Task description**
Create the about page. The page is simple and its parts are not reused, so Oznur wanted to do the whole thing.

**Subtasks**
Put the subtasks here if any (optional)

**Screenshots**
We might wanna pick the orange theme since we changed the navbar to white. It's your call.
Screen Shot 2022-08-01 at 11 34 11 AM

**Link to the component on Figma**
https://www.figma.com/file/kFlcMi3jiTl8q2NFIudEmw/Pebble-(new)?node-id=1803%3A5658

### PR DESCRIPTION
**Pull request by oznuren**
…nent for team members

#43

# Related Issue

- Resolve #43

### CODE REVIEW

**Review by omerfarukatas — COMMENTED** [review]
Eline saglik Oznur. Below are my comments.

**HERO SECTION**

How big is the hero image size? It took close to a second to download in my case. I have a fast internet so this might be a problem for those with slower connections. I have been compressing the images that I uploaded to the repo. Would you mind compressing this one if you haven’t already? Since you are a Mac user, you can open the image in the preview app and easily compress there. See below.
Screen Shot 2022-08-07 at 4 36 38 PM

- As you might remember, we decided we would call the project “Pebble” instead of “Pebble Work”. Could you change the title accordingly?

- How would the title look with a bigger font weight? I think it can add significance. In the screenshot below, I made the title “font-medium” and removed “font-light” from the paragraph. What do you think?
Screen Shot 2022-08-07 at 4 52 55 PM

- The title and paragraph are too small in the tablet view. Can we make the fonts bigger? 

**OUR TEAM**

- I love how this looks on desktop view! The margins adapt to screen size very well.

- The cards get way too small in the tablet view. Could you work on this so this section adapts well to the tablet size? The cards can be made bigger to take up the ample empty space inside the container.
Screen Shot 2022-08-07 at 4 55 19 PM

**Review by DKatuk — COMMENTED** [review]
Hi Öznur, I agree with Jangis. Could you please create an about page and import AboutPage and TeamCards components?
Also, ESLint gives a warning about sorting. Could you please fix this? Thank you! 
I am also getting an error: Image is missing required "src" property, as you mentioned.

**Review by DKatuk — COMMENTED** [review]
Can we add Salah too? Other than this, everything looks great! Ellerine Sağlık :)

**Review by DKatuk — APPROVED** [review]
Looks great! :)

**Review by MayceAlazzawi — APPROVED** [review]

**Pull request merged**
